name: Pull Request
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm i -g npm@8

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test
